print("""
-----------------------------------------------------------------
✨ Reproducible Examples
-----------------------------------------------------------------
""".strip())

docker_build(
    'sample/service:dev',
    '.',
    match_in_env_vars=True,
)

k8s_yaml('k8s.yaml')

k8s_resource('scheduler', port_forwards='8801', labels=['components'])