apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app.kubernetes.io/name: sample
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: sample5978
# == Scheduler Service ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: app
  labels:
    app.kubernetes.io/name: sample
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: sample5978
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/part-of: sample5978
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: sample5978
    spec:
      serviceAccountName: scheduler-account
      containers:
      - name: scheduler
        image: sample/service:dev
        command: ["python", "-m", "services.scheduler.main"]
        ports:
        - containerPort: 8801
          protocol: TCP
        env:
        - name: WORKER_IMAGE
          value: sample/service:dev
        - name: WORKER_NAMESPACE
          value: app
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: sample5978
  ports:
  - protocol: TCP
    port: 8801
    targetPort: 8801
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-account
  namespace: app
  labels:
    app.kubernetes.io/name: sample
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: sample5978
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-scheduler
  namespace: app
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: app
subjects:
- kind: ServiceAccount
  name: scheduler-account
  namespace: app
roleRef:
  kind: Role
  name: worker-scheduler
  apiGroup: "rbac.authorization.k8s.io"