version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - gradio_app

  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "7860"